/*
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.12.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.pessoa.pojos.E006pai;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E007ufs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-19T21:06:00.977Z")



public class E007ufs {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("nomUfs")
  private String nomUfs = null;

  @SerializedName("sigUfs")
  private String sigUfs = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("e006pai")
  private E006pai e006pai = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E007ufs usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E007ufs excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E007ufs nomUfs(String nomUfs) {
    this.nomUfs = nomUfs;
    return this;
  }

   /**
   * Nome
   * @return nomUfs
  **/
  @ApiModelProperty(value = "Nome")
  public String getNomUfs() {
    return nomUfs;
  }

  public void setNomUfs(String nomUfs) {
    this.nomUfs = nomUfs;
  }

  public E007ufs sigUfs(String sigUfs) {
    this.sigUfs = sigUfs;
    return this;
  }

   /**
   * Sigla
   * @return sigUfs
  **/
  @ApiModelProperty(value = "Sigla")
  public String getSigUfs() {
    return sigUfs;
  }

  public void setSigUfs(String sigUfs) {
    this.sigUfs = sigUfs;
  }

  public E007ufs dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E007ufs dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E007ufs id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E007ufs e006pai(E006pai e006pai) {
    this.e006pai = e006pai;
    return this;
  }

   /**
   * Get e006pai
   * @return e006pai
  **/
  @ApiModelProperty(value = "")
  public E006pai getE006pai() {
    return e006pai;
  }

  public void setE006pai(E006pai e006pai) {
    this.e006pai = e006pai;
  }

  public E007ufs usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E007ufs e007ufs = (E007ufs) o;
    return Objects.equals(this.usualt, e007ufs.usualt) &&
        Objects.equals(this.excluido, e007ufs.excluido) &&
        Objects.equals(this.nomUfs, e007ufs.nomUfs) &&
        Objects.equals(this.sigUfs, e007ufs.sigUfs) &&
        Objects.equals(this.dthger, e007ufs.dthger) &&
        Objects.equals(this.dthalt, e007ufs.dthalt) &&
        Objects.equals(this.id, e007ufs.id) &&
        Objects.equals(this.e006pai, e007ufs.e006pai) &&
        Objects.equals(this.usuger, e007ufs.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, excluido, nomUfs, sigUfs, dthger, dthalt, id, e006pai, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E007ufs {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    nomUfs: ").append(toIndentedString(nomUfs)).append("\n");
    sb.append("    sigUfs: ").append(toIndentedString(sigUfs)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    e006pai: ").append(toIndentedString(e006pai)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

