/*
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.10.6
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E026ram
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-25T10:49:01.055Z")



public class E026ram {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("desRam")
  private String desRam = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("codRam")
  private String codRam = null;

  @SerializedName("abrRam")
  private String abrRam = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E026ram usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E026ram excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E026ram dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E026ram desRam(String desRam) {
    this.desRam = desRam;
    return this;
  }

   /**
   * Descrição
   * @return desRam
  **/
  @ApiModelProperty(value = "Descrição")
  public String getDesRam() {
    return desRam;
  }

  public void setDesRam(String desRam) {
    this.desRam = desRam;
  }

  public E026ram dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E026ram id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E026ram codRam(String codRam) {
    this.codRam = codRam;
    return this;
  }

   /**
   * Ramo Atividade
   * @return codRam
  **/
  @ApiModelProperty(value = "Ramo Atividade")
  public String getCodRam() {
    return codRam;
  }

  public void setCodRam(String codRam) {
    this.codRam = codRam;
  }

  public E026ram abrRam(String abrRam) {
    this.abrRam = abrRam;
    return this;
  }

   /**
   * Abreviatura
   * @return abrRam
  **/
  @ApiModelProperty(value = "Abreviatura")
  public String getAbrRam() {
    return abrRam;
  }

  public void setAbrRam(String abrRam) {
    this.abrRam = abrRam;
  }

  public E026ram usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E026ram e026ram = (E026ram) o;
    return Objects.equals(this.usualt, e026ram.usualt) &&
        Objects.equals(this.excluido, e026ram.excluido) &&
        Objects.equals(this.dthger, e026ram.dthger) &&
        Objects.equals(this.desRam, e026ram.desRam) &&
        Objects.equals(this.dthalt, e026ram.dthalt) &&
        Objects.equals(this.id, e026ram.id) &&
        Objects.equals(this.codRam, e026ram.codRam) &&
        Objects.equals(this.abrRam, e026ram.abrRam) &&
        Objects.equals(this.usuger, e026ram.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, excluido, dthger, desRam, dthalt, id, codRam, abrRam, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E026ram {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    desRam: ").append(toIndentedString(desRam)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    codRam: ").append(toIndentedString(codRam)).append("\n");
    sb.append("    abrRam: ").append(toIndentedString(abrRam)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

