/*
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.pessoa.pojos.E030ban;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E030age
 */




public class E030age {
  @SerializedName("nomAge")
  private String nomAge = null;

  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("e030ban")
  private E030ban e030ban = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("codAge")
  private String codAge = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E030age nomAge(String nomAge) {
    this.nomAge = nomAge;
    return this;
  }

   /**
   * Nome da agência
   * @return nomAge
  **/
  @ApiModelProperty(value = "Nome da agência")
  public String getNomAge() {
    return nomAge;
  }

  public void setNomAge(String nomAge) {
    this.nomAge = nomAge;
  }

  public E030age usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E030age excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluido ?
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluido ?")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E030age e030ban(E030ban e030ban) {
    this.e030ban = e030ban;
    return this;
  }

   /**
   * Get e030ban
   * @return e030ban
  **/
  @ApiModelProperty(value = "")
  public E030ban getE030ban() {
    return e030ban;
  }

  public void setE030ban(E030ban e030ban) {
    this.e030ban = e030ban;
  }

  public E030age dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E030age dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E030age id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E030age codAge(String codAge) {
    this.codAge = codAge;
    return this;
  }

   /**
   * Código
   * @return codAge
  **/
  @ApiModelProperty(value = "Código")
  public String getCodAge() {
    return codAge;
  }

  public void setCodAge(String codAge) {
    this.codAge = codAge;
  }

  public E030age usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E030age e030age = (E030age) o;
    return Objects.equals(this.nomAge, e030age.nomAge) &&
        Objects.equals(this.usualt, e030age.usualt) &&
        Objects.equals(this.excluido, e030age.excluido) &&
        Objects.equals(this.e030ban, e030age.e030ban) &&
        Objects.equals(this.dthger, e030age.dthger) &&
        Objects.equals(this.dthalt, e030age.dthalt) &&
        Objects.equals(this.id, e030age.id) &&
        Objects.equals(this.codAge, e030age.codAge) &&
        Objects.equals(this.usuger, e030age.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nomAge, usualt, excluido, e030ban, dthger, dthalt, id, codAge, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E030age {\n");
    
    sb.append("    nomAge: ").append(toIndentedString(nomAge)).append("\n");
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    e030ban: ").append(toIndentedString(e030ban)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    codAge: ").append(toIndentedString(codAge)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

