/*
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.pessoa.pojos.E001pes;
import br.com.senior.erpx.fnd.pessoa.pojos.EnumCifFob;
import br.com.senior.erpx.fnd.pessoa.pojos.EnumSitReg;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E073pes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-03T13:41:01.573Z")



public class E073pes {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("e001pes")
  private E001pes e001pes = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("usuger")
  private String usuger = null;

  @SerializedName("nomCto")
  private String nomCto = null;

  @SerializedName("nrnTrc")
  private String nrnTrc = null;

  @SerializedName("nroRes")
  private String nroRes = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("codTaf")
  private String codTaf = null;

  @SerializedName("cifFob")
  private EnumCifFob cifFob = null;

  @SerializedName("sitTra")
  private EnumSitReg sitTra = null;

  public E073pes usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E073pes excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E073pes dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E073pes e001pes(E001pes e001pes) {
    this.e001pes = e001pes;
    return this;
  }

   /**
   * Get e001pes
   * @return e001pes
  **/
  @ApiModelProperty(value = "")
  public E001pes getE001pes() {
    return e001pes;
  }

  public void setE001pes(E001pes e001pes) {
    this.e001pes = e001pes;
  }

  public E073pes dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E073pes usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }

  public E073pes nomCto(String nomCto) {
    this.nomCto = nomCto;
    return this;
  }

   /**
   * Nome da pessoa de contato na transportadora
   * @return nomCto
  **/
  @ApiModelProperty(value = "Nome da pessoa de contato na transportadora")
  public String getNomCto() {
    return nomCto;
  }

  public void setNomCto(String nomCto) {
    this.nomCto = nomCto;
  }

  public E073pes nrnTrc(String nrnTrc) {
    this.nrnTrc = nrnTrc;
    return this;
  }

   /**
   * Registro nacional de transportadores rodoviários de carga - RNTRC
   * @return nrnTrc
  **/
  @ApiModelProperty(value = "Registro nacional de transportadores rodoviários de carga - RNTRC")
  public String getNrnTrc() {
    return nrnTrc;
  }

  public void setNrnTrc(String nrnTrc) {
    this.nrnTrc = nrnTrc;
  }

  public E073pes nroRes(String nroRes) {
    this.nroRes = nroRes;
    return this;
  }

   /**
   * Número de registro adquirido junto a administração estadual
   * @return nroRes
  **/
  @ApiModelProperty(value = "Número de registro adquirido junto a administração estadual")
  public String getNroRes() {
    return nroRes;
  }

  public void setNroRes(String nroRes) {
    this.nroRes = nroRes;
  }

  public E073pes id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E073pes codTaf(String codTaf) {
    this.codTaf = codTaf;
    return this;
  }

   /**
   * Termo de autorização dos serviços em regime de fretamento - TAF
   * @return codTaf
  **/
  @ApiModelProperty(value = "Termo de autorização dos serviços em regime de fretamento - TAF")
  public String getCodTaf() {
    return codTaf;
  }

  public void setCodTaf(String codTaf) {
    this.codTaf = codTaf;
  }

  public E073pes cifFob(EnumCifFob cifFob) {
    this.cifFob = cifFob;
    return this;
  }

   /**
   * Get cifFob
   * @return cifFob
  **/
  @ApiModelProperty(value = "")
  public EnumCifFob getCifFob() {
    return cifFob;
  }

  public void setCifFob(EnumCifFob cifFob) {
    this.cifFob = cifFob;
  }

  public E073pes sitTra(EnumSitReg sitTra) {
    this.sitTra = sitTra;
    return this;
  }

   /**
   * Get sitTra
   * @return sitTra
  **/
  @ApiModelProperty(value = "")
  public EnumSitReg getSitTra() {
    return sitTra;
  }

  public void setSitTra(EnumSitReg sitTra) {
    this.sitTra = sitTra;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E073pes e073pes = (E073pes) o;
    return Objects.equals(this.usualt, e073pes.usualt) &&
        Objects.equals(this.excluido, e073pes.excluido) &&
        Objects.equals(this.dthger, e073pes.dthger) &&
        Objects.equals(this.e001pes, e073pes.e001pes) &&
        Objects.equals(this.dthalt, e073pes.dthalt) &&
        Objects.equals(this.usuger, e073pes.usuger) &&
        Objects.equals(this.nomCto, e073pes.nomCto) &&
        Objects.equals(this.nrnTrc, e073pes.nrnTrc) &&
        Objects.equals(this.nroRes, e073pes.nroRes) &&
        Objects.equals(this.id, e073pes.id) &&
        Objects.equals(this.codTaf, e073pes.codTaf) &&
        Objects.equals(this.cifFob, e073pes.cifFob) &&
        Objects.equals(this.sitTra, e073pes.sitTra);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, excluido, dthger, e001pes, dthalt, usuger, nomCto, nrnTrc, nroRes, id, codTaf, cifFob, sitTra);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E073pes {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    e001pes: ").append(toIndentedString(e001pes)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("    nomCto: ").append(toIndentedString(nomCto)).append("\n");
    sb.append("    nrnTrc: ").append(toIndentedString(nrnTrc)).append("\n");
    sb.append("    nroRes: ").append(toIndentedString(nroRes)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    codTaf: ").append(toIndentedString(codTaf)).append("\n");
    sb.append("    cifFob: ").append(toIndentedString(cifFob)).append("\n");
    sb.append("    sitTra: ").append(toIndentedString(sitTra)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

