/*
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.12.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.pessoa.pojos.E001pes;
import br.com.senior.erpx.fnd.pessoa.pojos.E030age;
import br.com.senior.erpx.fnd.pessoa.pojos.E030ban;
import br.com.senior.erpx.fnd.pessoa.pojos.EnumSitReg;
import br.com.senior.erpx.fnd.pessoa.pojos.EnumTipTcc;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E077pes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-19T21:06:00.977Z")



public class E077pes {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("e030ban")
  private E030ban e030ban = null;

  @SerializedName("tipTcc")
  private EnumTipTcc tipTcc = null;

  @SerializedName("e030age")
  private E030age e030age = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("sitFav")
  private EnumSitReg sitFav = null;

  @SerializedName("e001pes")
  private E001pes e001pes = null;

  @SerializedName("ccbFav")
  private String ccbFav = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E077pes usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E077pes excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E077pes e030ban(E030ban e030ban) {
    this.e030ban = e030ban;
    return this;
  }

   /**
   * Get e030ban
   * @return e030ban
  **/
  @ApiModelProperty(value = "")
  public E030ban getE030ban() {
    return e030ban;
  }

  public void setE030ban(E030ban e030ban) {
    this.e030ban = e030ban;
  }

  public E077pes tipTcc(EnumTipTcc tipTcc) {
    this.tipTcc = tipTcc;
    return this;
  }

   /**
   * Get tipTcc
   * @return tipTcc
  **/
  @ApiModelProperty(value = "")
  public EnumTipTcc getTipTcc() {
    return tipTcc;
  }

  public void setTipTcc(EnumTipTcc tipTcc) {
    this.tipTcc = tipTcc;
  }

  public E077pes e030age(E030age e030age) {
    this.e030age = e030age;
    return this;
  }

   /**
   * Get e030age
   * @return e030age
  **/
  @ApiModelProperty(value = "")
  public E030age getE030age() {
    return e030age;
  }

  public void setE030age(E030age e030age) {
    this.e030age = e030age;
  }

  public E077pes dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E077pes sitFav(EnumSitReg sitFav) {
    this.sitFav = sitFav;
    return this;
  }

   /**
   * Get sitFav
   * @return sitFav
  **/
  @ApiModelProperty(value = "")
  public EnumSitReg getSitFav() {
    return sitFav;
  }

  public void setSitFav(EnumSitReg sitFav) {
    this.sitFav = sitFav;
  }

  public E077pes e001pes(E001pes e001pes) {
    this.e001pes = e001pes;
    return this;
  }

   /**
   * Get e001pes
   * @return e001pes
  **/
  @ApiModelProperty(value = "")
  public E001pes getE001pes() {
    return e001pes;
  }

  public void setE001pes(E001pes e001pes) {
    this.e001pes = e001pes;
  }

  public E077pes ccbFav(String ccbFav) {
    this.ccbFav = ccbFav;
    return this;
  }

   /**
   * Número da conta corrente do favorecido no banco
   * @return ccbFav
  **/
  @ApiModelProperty(value = "Número da conta corrente do favorecido no banco")
  public String getCcbFav() {
    return ccbFav;
  }

  public void setCcbFav(String ccbFav) {
    this.ccbFav = ccbFav;
  }

  public E077pes dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E077pes id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E077pes usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E077pes e077pes = (E077pes) o;
    return Objects.equals(this.usualt, e077pes.usualt) &&
        Objects.equals(this.excluido, e077pes.excluido) &&
        Objects.equals(this.e030ban, e077pes.e030ban) &&
        Objects.equals(this.tipTcc, e077pes.tipTcc) &&
        Objects.equals(this.e030age, e077pes.e030age) &&
        Objects.equals(this.dthger, e077pes.dthger) &&
        Objects.equals(this.sitFav, e077pes.sitFav) &&
        Objects.equals(this.e001pes, e077pes.e001pes) &&
        Objects.equals(this.ccbFav, e077pes.ccbFav) &&
        Objects.equals(this.dthalt, e077pes.dthalt) &&
        Objects.equals(this.id, e077pes.id) &&
        Objects.equals(this.usuger, e077pes.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, excluido, e030ban, tipTcc, e030age, dthger, sitFav, e001pes, ccbFav, dthalt, id, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E077pes {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    e030ban: ").append(toIndentedString(e030ban)).append("\n");
    sb.append("    tipTcc: ").append(toIndentedString(tipTcc)).append("\n");
    sb.append("    e030age: ").append(toIndentedString(e030age)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    sitFav: ").append(toIndentedString(sitFav)).append("\n");
    sb.append("    e001pes: ").append(toIndentedString(e001pes)).append("\n");
    sb.append("    ccbFav: ").append(toIndentedString(ccbFav)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

