/*
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.12.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.pessoa.pojos.E001pes;
import br.com.senior.erpx.fnd.pessoa.pojos.E021mot;
import br.com.senior.erpx.fnd.pessoa.pojos.EnumSitReg;
import br.com.senior.erpx.fnd.pessoa.pojos.EnumTipAce;
import br.com.senior.erpx.fnd.pessoa.pojos.EnumTipEmc;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E085pes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-19T21:05:01.247Z")



public class E085pes {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("tipAce")
  private EnumTipAce tipAce = null;

  @SerializedName("e001pes")
  private E001pes e001pes = null;

  @SerializedName("marCli")
  private String marCli = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("usuMot")
  private String usuMot = null;

  @SerializedName("dthMot")
  private OffsetDateTime dthMot = null;

  @SerializedName("tipEmc")
  private EnumTipEmc tipEmc = null;

  @SerializedName("usuger")
  private String usuger = null;

  @SerializedName("obsMot")
  private String obsMot = null;

  @SerializedName("sitCli")
  private EnumSitReg sitCli = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("e021mot")
  private E021mot e021mot = null;

  public E085pes usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E085pes excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E085pes dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E085pes tipAce(EnumTipAce tipAce) {
    this.tipAce = tipAce;
    return this;
  }

   /**
   * Get tipAce
   * @return tipAce
  **/
  @ApiModelProperty(value = "")
  public EnumTipAce getTipAce() {
    return tipAce;
  }

  public void setTipAce(EnumTipAce tipAce) {
    this.tipAce = tipAce;
  }

  public E085pes e001pes(E001pes e001pes) {
    this.e001pes = e001pes;
    return this;
  }

   /**
   * Get e001pes
   * @return e001pes
  **/
  @ApiModelProperty(value = "")
  public E001pes getE001pes() {
    return e001pes;
  }

  public void setE001pes(E001pes e001pes) {
    this.e001pes = e001pes;
  }

  public E085pes marCli(String marCli) {
    this.marCli = marCli;
    return this;
  }

   /**
   * Marca do cliente
   * @return marCli
  **/
  @ApiModelProperty(value = "Marca do cliente")
  public String getMarCli() {
    return marCli;
  }

  public void setMarCli(String marCli) {
    this.marCli = marCli;
  }

  public E085pes dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E085pes usuMot(String usuMot) {
    this.usuMot = usuMot;
    return this;
  }

   /**
   * Usuário responsável pelo motivo da situação do cliente
   * @return usuMot
  **/
  @ApiModelProperty(value = "Usuário responsável pelo motivo da situação do cliente")
  public String getUsuMot() {
    return usuMot;
  }

  public void setUsuMot(String usuMot) {
    this.usuMot = usuMot;
  }

  public E085pes dthMot(OffsetDateTime dthMot) {
    this.dthMot = dthMot;
    return this;
  }

   /**
   * Data do motivo da situação do cliente
   * @return dthMot
  **/
  @ApiModelProperty(value = "Data do motivo da situação do cliente")
  public OffsetDateTime getDthMot() {
    return dthMot;
  }

  public void setDthMot(OffsetDateTime dthMot) {
    this.dthMot = dthMot;
  }

  public E085pes tipEmc(EnumTipEmc tipEmc) {
    this.tipEmc = tipEmc;
    return this;
  }

   /**
   * Get tipEmc
   * @return tipEmc
  **/
  @ApiModelProperty(value = "")
  public EnumTipEmc getTipEmc() {
    return tipEmc;
  }

  public void setTipEmc(EnumTipEmc tipEmc) {
    this.tipEmc = tipEmc;
  }

  public E085pes usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }

  public E085pes obsMot(String obsMot) {
    this.obsMot = obsMot;
    return this;
  }

   /**
   * Observação do motivo da situação do cliente
   * @return obsMot
  **/
  @ApiModelProperty(value = "Observação do motivo da situação do cliente")
  public String getObsMot() {
    return obsMot;
  }

  public void setObsMot(String obsMot) {
    this.obsMot = obsMot;
  }

  public E085pes sitCli(EnumSitReg sitCli) {
    this.sitCli = sitCli;
    return this;
  }

   /**
   * Get sitCli
   * @return sitCli
  **/
  @ApiModelProperty(value = "")
  public EnumSitReg getSitCli() {
    return sitCli;
  }

  public void setSitCli(EnumSitReg sitCli) {
    this.sitCli = sitCli;
  }

  public E085pes id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E085pes e021mot(E021mot e021mot) {
    this.e021mot = e021mot;
    return this;
  }

   /**
   * Get e021mot
   * @return e021mot
  **/
  @ApiModelProperty(value = "")
  public E021mot getE021mot() {
    return e021mot;
  }

  public void setE021mot(E021mot e021mot) {
    this.e021mot = e021mot;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E085pes e085pes = (E085pes) o;
    return Objects.equals(this.usualt, e085pes.usualt) &&
        Objects.equals(this.excluido, e085pes.excluido) &&
        Objects.equals(this.dthger, e085pes.dthger) &&
        Objects.equals(this.tipAce, e085pes.tipAce) &&
        Objects.equals(this.e001pes, e085pes.e001pes) &&
        Objects.equals(this.marCli, e085pes.marCli) &&
        Objects.equals(this.dthalt, e085pes.dthalt) &&
        Objects.equals(this.usuMot, e085pes.usuMot) &&
        Objects.equals(this.dthMot, e085pes.dthMot) &&
        Objects.equals(this.tipEmc, e085pes.tipEmc) &&
        Objects.equals(this.usuger, e085pes.usuger) &&
        Objects.equals(this.obsMot, e085pes.obsMot) &&
        Objects.equals(this.sitCli, e085pes.sitCli) &&
        Objects.equals(this.id, e085pes.id) &&
        Objects.equals(this.e021mot, e085pes.e021mot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, excluido, dthger, tipAce, e001pes, marCli, dthalt, usuMot, dthMot, tipEmc, usuger, obsMot, sitCli, id, e021mot);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E085pes {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    tipAce: ").append(toIndentedString(tipAce)).append("\n");
    sb.append("    e001pes: ").append(toIndentedString(e001pes)).append("\n");
    sb.append("    marCli: ").append(toIndentedString(marCli)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    usuMot: ").append(toIndentedString(usuMot)).append("\n");
    sb.append("    dthMot: ").append(toIndentedString(dthMot)).append("\n");
    sb.append("    tipEmc: ").append(toIndentedString(tipEmc)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("    obsMot: ").append(toIndentedString(obsMot)).append("\n");
    sb.append("    sitCli: ").append(toIndentedString(sitCli)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    e021mot: ").append(toIndentedString(e021mot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

