/*
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets enumAplMot
 */
@JsonAdapter(EnumAplMot.Adapter.class)
public enum EnumAplMot {
  
  V1("V1"),
  
  V2("V2"),
  
  V3("V3"),
  
  V4("V4"),
  
  V5("V5"),
  
  V6("V6"),
  
  V8("V8"),
  
  V9("V9"),
  
  V11("V11"),
  
  V12("V12"),
  
  V13("V13"),
  
  V14("V14"),
  
  V20("V20"),
  
  V36("V36"),
  
  V40("V40"),
  
  V42("V42"),
  
  V43("V43"),
  
  V44("V44"),
  
  V45("V45"),
  
  V46("V46"),
  
  V49("V49"),
  
  V51("V51"),
  
  V52("V52"),
  
  V99("V99");

  private String value;

  EnumAplMot(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EnumAplMot fromValue(String text) {
    for (EnumAplMot b : EnumAplMot.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EnumAplMot> {
    @Override
    public void write(final JsonWriter jsonWriter, final EnumAplMot enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EnumAplMot read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EnumAplMot.fromValue(String.valueOf(value));
    }
  }
}

