/*
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.12.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets enumIndNif
 */
@JsonAdapter(EnumIndNif.Adapter.class)
public enum EnumIndNif {
  
  V1("V1"),
  
  V2("V2"),
  
  V3("V3");

  private String value;

  EnumIndNif(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EnumIndNif fromValue(String text) {
    for (EnumIndNif b : EnumIndNif.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EnumIndNif> {
    @Override
    public void write(final JsonWriter jsonWriter, final EnumIndNif enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EnumIndNif read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EnumIndNif.fromValue(String.valueOf(value));
    }
  }
}

