/*
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.10.6
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.pessoa.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets enumTipMer
 */
@JsonAdapter(EnumTipMer.Adapter.class)
public enum EnumTipMer {
  
  VI("VI"),
  
  VE("VE");

  private String value;

  EnumTipMer(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EnumTipMer fromValue(String text) {
    for (EnumTipMer b : EnumTipMer.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EnumTipMer> {
    @Override
    public void write(final JsonWriter jsonWriter, final EnumTipMer enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EnumTipMer read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EnumTipMer.fromValue(String.valueOf(value));
    }
  }
}

